{
  "latest_version": [
    "3.0"
  ],
  "meta": {
    "description": "zExceptions contains common exceptions used in Zope2",
    "homepage": "http://pypi.python.org/pypi/zExceptions",
    "license": "ZPL 2.1"
  },
  "versions": {
    "2.13.0": {
      "sha256": "66d8393f97dbbaf75f440b358cd88a413892c743866bb0b2468afb6247f9f610",
      "url": "https://files.pythonhosted.org/packages/4b/86/110ab12c402082dc05cd5c121ab26d64a184477c6e3150c77edc0cfc4aef/zExceptions-2.13.0.zip"
    },
    "3.0": {
      "sha256": "582370f976f17082d9826528dbcfb764092de983a58853365a98ab27dfb5dda9",
      "url": "https://files.pythonhosted.org/packages/1e/66/929554bd50a581456986d68bb750eded5a92bdd11767cc4d024fa5f33704/zExceptions-3.0.zip"
    }
  }
}