{
  "latest_version": [
    "4.0.8"
  ],
  "meta": {
    "description": "Zope Exceptions",
    "homepage": "http://cheeseshop.python.org/pypi/zope.exceptions",
    "license": "ZPL 2.1"
  },
  "versions": {
    "3.4.0": {
      "sha256": "497850c66f0a0cd1dadddd8e6db22ee6bc1fc8b1d0637c8a8ccb217c900de39f",
      "url": "https://files.pythonhosted.org/packages/9a/0a/bc0d8289c17917a8c34cda4b3dcf944cb37c6476a3a634c6c697712030c8/zope.exceptions-3.4.0.tar.gz"
    },
    "3.4dev": {
      "sha256": "01b4cb64999daca51f2a8994bf6dde7bbef221e6d4b902a9b2804401e95ed8aa",
      "url": "https://files.pythonhosted.org/packages/45/d0/cb9012118410142830b0bf3d38a560155d08c7bd34fb954638a18bd68da9/zope.exceptions-3.4dev-r73107.tar.gz"
    },
    "3.5.0": {
      "sha256": "43b726d8fe2e06189c13e1fd977b3e0c3e476d3836d0787335e56436418e5cd6",
      "url": "https://files.pythonhosted.org/packages/82/46/24c869fa48821cd2b113830d329acb83a4149cbcdefdab179694a6176151/zope.exceptions-3.5.0.tar.gz"
    },
    "3.5.1": {
      "sha256": "4eac1bb65e4548f815b04c07011561aa4e57187cb31f7c3ca24b3d81aca7416d",
      "url": "https://files.pythonhosted.org/packages/d4/9c/357e23099b0297078fbfc256c22da9a5d9d6dfb5aa6d65e59697ad0148aa/zope.exceptions-3.5.1.tar.gz"
    },
    "3.5.2": {
      "sha256": "cd7b0abd38d654d5905d62b867641ef2d19740831d00704bc4c534ab9fc28390",
      "url": "https://files.pythonhosted.org/packages/3e/2b/5d4f7e37e73ef86defba6502c3190b40e9ef2247e2c9691c9832e3c4bd41/zope.exceptions-3.5.2.tar.gz"
    },
    "3.6.0": {
      "sha256": "4ad8604f944dc51ae21b1f398f69ce236de2dcec1ebb1c2ee230873d52ea9002",
      "url": "https://files.pythonhosted.org/packages/d6/a4/1cba5fd50739c660d1bc2e12cd27d9e2c06d6fe648dd54d9d1c20b627ed9/zope.exceptions-3.6.0.tar.gz"
    },
    "3.6.1": {
      "sha256": "a6d0c50f8103b2e89bc6c606fe97ed84b0cbe09e08b8a537a8909ab712fbf3e6",
      "url": "https://files.pythonhosted.org/packages/36/ff/1792a6dbc8e8f88ea21d70b53fdc3f690118ea10a0462ecb9efc7024b524/zope.exceptions-3.6.1.zip"
    },
    "3.6.2": {
      "sha256": "ba8618991341ead4b726bf7b8b9e5bbb47018f29c9923412c272b27e440c6ac5",
      "url": "https://files.pythonhosted.org/packages/01/03/3f240e293811e547b1adb6e2f3e3ad1412a6a125abaef21a517172e68595/zope.exceptions-3.6.2.tar.gz"
    },
    "3.7.0": {
      "sha256": "531e9aae5cf88598de88df549d3f9708a83c142f06dddf2117c5c9e8b35b3ce7",
      "url": "https://files.pythonhosted.org/packages/a7/63/9c0de0b732b7d9d0785411e1449b3a4167c3eb36bcd80e1d7839a187b8be/zope.exceptions-3.7.0.tar.gz"
    },
    "3.7.1": {
      "sha256": "f2c555ffc35aa503471d6200472a66dfed5fd54d38095f555aac6e1a09f80fa3",
      "url": "https://files.pythonhosted.org/packages/30/c0/c79cc3fa85c9fee7c0df5fb7652308dd9bce2604177adb813cc8c50645b4/zope.exceptions-3.7.1.tar.gz"
    },
    "4.0.0": {
      "sha256": "a9785fddaf61c8018a9f4a0763db0aeb2eaac827f62de7e44e46da3cd6a6fd4d",
      "url": "https://files.pythonhosted.org/packages/0d/18/28dd2b9957bdf53bb417fa1998fa543aa160acb1a60a0f5a2b11d95bff61/zope.exceptions-4.0.0.tar.gz"
    },
    "4.0.0.1": {
      "sha256": "6d86069fe18ef9671c2e68673f5a3ad2c46cd85d703f3abba3cb2e8d544beaa6",
      "url": "https://files.pythonhosted.org/packages/e3/46/72ad54d3b33657535383ab94792299463da0ee3a8770a16ea2902026118c/zope.exceptions-4.0.0.1.tar.gz"
    },
    "4.0.1": {
      "sha256": "dd59bc8efd03b59d53be35b621d1b61742c24a553af7c5aa3edc127cef38a9b2",
      "url": "https://files.pythonhosted.org/packages/78/4f/cae9f706b7713e7f8bf32eff23c64e58f5a6e38af3cd3888d2d612bc8ebf/zope.exceptions-4.0.1.zip"
    },
    "4.0.2": {
      "sha256": "9c08fb287d77446221182e9b05d065a82a9998e5a4e254d311de783846f0be26",
      "url": "https://files.pythonhosted.org/packages/4a/40/7622734d1252e174cbf4f23c674d855a049bb7f4a42ff080a87aa828375c/zope.exceptions-4.0.2.tar.gz"
    },
    "4.0.3": {
      "sha256": "f45a331594b940366c3a9ea0e3095c4a2959088b5a0f3107fcaaece67bf6242e",
      "url": "https://files.pythonhosted.org/packages/18/63/2cbd4881279f145b6a36c60ff1d10c653307cd694ce57722ce422903c4ef/zope.exceptions-4.0.3.zip"
    },
    "4.0.4": {
      "sha256": "549d2a1cda71297004c9f77343e4b0c37f6ca565ed8ee2d2cf9daa92165f518a",
      "url": "https://files.pythonhosted.org/packages/6a/29/0f95d3943d4994e53e9def04577b56015dece8e6c83324c5a23150a59816/zope.exceptions-4.0.4.zip"
    },
    "4.0.5": {
      "sha256": "519659de1b407b1dff255fd3985a1cd7685a827ac6314a78fa28ad3f2439171b",
      "url": "https://files.pythonhosted.org/packages/90/39/f8de8f1f8449f0943506ef74908988da4d43349db5f41984de5e662b0046/zope.exceptions-4.0.5.tar.gz"
    },
    "4.0.6": {
      "sha256": "35afae142d298b39efd84ad4c30c7676abcd78c2b1213c6006804b13d48db044",
      "url": "https://files.pythonhosted.org/packages/87/dd/4fbfaeac1a26a41b152016ba001ef226539aa9376897248b0b4129b4d183/zope.exceptions-4.0.6.zip"
    },
    "4.0.7": {
      "sha256": "98235d1a119ec0134076c20a827393c739532560a08f5670553ebf9a735238b8",
      "url": "https://files.pythonhosted.org/packages/5a/da/c44a29d6e8690709fb34a6f38e40ee03e766c27f81a7da4b16a18ed5a09b/zope.exceptions-4.0.7.tar.gz"
    },
    "4.0.8": {
      "sha256": "f43bcbb7e4f043565d4322db6ea50dd5a7b71cd03bb37f66791d6b6394529d7f",
      "url": "https://files.pythonhosted.org/packages/8f/b7/eba9eca6841fa47d9a30f71a602be7615bff4f8e11f85c2840b88a77c68a/zope.exceptions-4.0.8.tar.gz"
    }
  }
}