{
  "latest_version": [
    "3.1.1"
  ],
  "meta": {
    "description": "Wrappers for the framework ExceptionHandling on Mac OS X",
    "homepage": "http://pyobjc.sourceforge.net",
    "license": "MIT License"
  },
  "versions": [
    {
      "2.2": {
        "sha256": "839ea74b9d5b99d8aa635b04185adce61eecf3df078fdef00e3bfde04fa0c60f",
        "url": "https://files.pythonhosted.org/packages/79/df/1d5c72060da696bedee49e9fa92baf1809c0b93124fc73f0a34e69edc4a9/pyobjc-framework-ExceptionHandling-2.2.tar.gz"
      },
      "2.2b1": {
        "sha256": "cabf1fbdfb50ab2bd03c0b758ee990cb36b8d7a766e4c1aaceb0ac247ddb37a8",
        "url": "https://files.pythonhosted.org/packages/7a/d6/abfafa1a000862886c3f06d090c29663ca560b46d3e6e2eccaa4dc44f3ef/pyobjc-framework-ExceptionHandling-2.2b1.tar.gz"
      },
      "2.2b2": {
        "sha256": "d695afbcab18c5f65096212c7da9efee6ff797a9949930095682451be0c12b75",
        "url": "https://files.pythonhosted.org/packages/4e/17/28f231665c02c1d947dc43885f1285399bdacb653e8fb11f0b3b0d4207f7/pyobjc-framework-ExceptionHandling-2.2b2.tar.gz"
      },
      "2.3": {
        "sha256": "3dd39543eb8639267cb3cb02685b159744bf10ea733a104d4c8a1554b96952b5",
        "url": "https://files.pythonhosted.org/packages/22/fe/7ae2cdffd55b33274faea7e7e97ac8614e65306233c93b00e9706246ba4d/pyobjc-framework-ExceptionHandling-2.3.tar.gz"
      },
      "2.4": {
        "sha256": "a09cab7654b4ec76349c55761efdb0225e6a00018622a82a394b4b45f54166dc",
        "url": "https://files.pythonhosted.org/packages/e9/c8/6077eeb24fe79f97c9f33aa342fa13dffb3c7f4fc6558c87ba04f08756b8/pyobjc-framework-ExceptionHandling-2.4.tar.gz"
      },
      "2.5.1": {
        "sha256": "fa943afe83357a514834cab5a99af8db77d18817f79414032da90656a7f08281",
        "url": "https://files.pythonhosted.org/packages/82/2c/135c86b68f487aea34191123e6ae08fad54d389b9908f76394d49210d2c2/pyobjc-framework-ExceptionHandling-2.5.1.tar.gz"
      },
      "3.0.1": {
        "sha256": "c25e33170cc5c5e02e78d8336db80c592eeae2aaef81bfc8e11b5cfc892bb96d",
        "url": "https://files.pythonhosted.org/packages/15/c8/12ff4491e585297898c4edc88eeabe408c17916fe31b444c8c82314d3d46/pyobjc-framework-ExceptionHandling-3.0.1.tar.gz"
      },
      "3.0.3": {
        "sha256": "9325a62a56216f6ffdd5bacef1d125c56d7805a2e89343eab52163a3e7327ce2",
        "url": "https://files.pythonhosted.org/packages/d3/48/388954e938b3e545a47b4a8ca0c41fee6006877a8caf99e94453b25c3b3d/pyobjc-framework-ExceptionHandling-3.0.3.tar.gz"
      },
      "3.0.4": {
        "sha256": "ccc5a85dd3aa00196c5087090bec1a1cf458387a6538ab654a62bf5e2ac93e89",
        "url": "https://files.pythonhosted.org/packages/85/ec/b13e3464d9bb4d3a6ad1ebe25b66bb9a1e7c2b2df68858a9df0a4f379546/pyobjc-framework-ExceptionHandling-3.0.4.tar.gz"
      },
      "3.1": {
        "sha256": "76c571c5f44809f6fcebbdde2484359a14d61f92931257a3a6816c468115f73f",
        "url": "https://files.pythonhosted.org/packages/0c/ac/5fa234422fcca9d5512bf18cc40bac30cf451a47a5841de8c16acf209518/pyobjc-framework-ExceptionHandling-3.1.tar.gz"
      },
      "3.1.1": {
        "sha256": "f8e18cb7f2a0bde38d3c36736645826f66c5fe3c738eeed8ba366dbe520c825f",
        "url": "https://files.pythonhosted.org/packages/2b/91/8d46c724b8248d0f9c6accb4423c1fb4666b8dc60b371d7e7ff34313b901/pyobjc-framework-ExceptionHandling-3.1.1.tar.gz"
      }
    }
  ]
}