{
  "latest_version": [
    "1.0"
  ],
  "meta": {
    "description": "ZODB: recover lost objects from a backup",
    "homepage": "http://pypi.python.org/pypi/dm.zodb.repair",
    "license": "ZPL"
  },
  "versions": {
    "1.0": {
      "sha256": "c0e3cf6496f63768d1f271cc86c16c47ec04ce1b3726ccfbb168cdeb6f8bbfcc",
      "url": "https://files.pythonhosted.org/packages/e2/73/9fcbb68352ecd1d6a820a3c87c3c9ba6fd4c10fee1e39e6c9c5f9c593a53/dm.zodb.repair-1.0.tar.gz"
    }
  }
}