{
  "latest_version": [
    "1.0.1"
  ],
  "meta": {
    "description": "Patch ZODB to work around https://github.com/zopefoundation/ZODB3/issues/2",
    "homepage": "http://pypi.python.org/pypi/dm.zodbpatches.commit_savepoint",
    "license": "ZPL"
  },
  "versions": [
    {
      "1.0": {
        "sha256": "36a1a9fe8b327ba7bacc15612d6933017bd16846fd11b5e85cd54360c8493e1c",
        "url": "https://files.pythonhosted.org/packages/ea/eb/a8c93386081091f104aec4d04304a508986d767a492cd3148cb071508db4/dm.zodbpatches.commit_savepoint-1.0.tar.gz"
      },
      "1.0.1": {
        "sha256": "e44153eaa727e4fc74b587535540605c7454ce52fd7919805c7f140eef3cfead",
        "url": "https://files.pythonhosted.org/packages/50/ce/2a977abd08de2e83ba99848b524a05ebd389dc2c677bec6120bda09ce3a5/dm.zodbpatches.commit_savepoint-1.0.1.tar.gz"
      }
    }
  ]
}