{
  "latest_version": [
    "1.1"
  ],
  "meta": {
    "description": "Try to fix http://plone.org/products/linguaplone/issues/273",
    "homepage": "http://svn.plone.org/svn/collective/",
    "license": "GPL"
  },
  "versions": [
    {
      "1.0": {
        "sha256": "397241faeb072dc502f425ad90c8d80ea5229933e6107bf0257ca8e14a42e3b2",
        "url": "https://files.pythonhosted.org/packages/7a/a0/7444707b7e229271de52cc3458d2fb459369ba033b35a8f49e109948adab/collective.patchlinguaploneissue273-1.0.zip"
      },
      "1.1": {
        "sha256": "53735301da0c70c988dd88ee9e3d17f3b3e0a72c9eb8ecea6b47e128f50f63bf",
        "url": "https://files.pythonhosted.org/packages/f2/8a/c8d5797ec3e91c1a1e76aca803b8bc1128618161865f8442a36c68c3a7e5/collective.patchlinguaploneissue273-1.1.zip"
      }
    }
  ]
}